env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - tab
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-trailing-spaces: "error"
  no-console: 0
globals:
  vinage: false
  canvas: false
  ipaddr: false
  game: false
  ownIdx: true
  players: true
  shots: true
  message: false
  Player: true
  Planet: false
  Enemy: false
  Shot: false
  weapon: false
  resources: true
